//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appendix_Report
    {
        public int Id { get; set; }
        public int AppendixId { get; set; }
        public int ReportTypeId { get; set; }
    }
}
