//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportColumn
    {
        public int Id { get; set; }
        public int RowId { get; set; }
        public Nullable<decimal> Value1 { get; set; }
        public Nullable<decimal> Value2 { get; set; }
        public Nullable<decimal> Value3 { get; set; }
        public Nullable<decimal> Value4 { get; set; }
        public Nullable<decimal> Value5 { get; set; }
        public Nullable<decimal> Value6 { get; set; }
        public Nullable<decimal> Value7 { get; set; }
        public Nullable<decimal> Value8 { get; set; }
        public Nullable<decimal> Value9 { get; set; }
    
        public virtual ReportRow ReportRow { get; set; }
    }
}
