//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportRow()
        {
            this.ReportColumns = new HashSet<ReportColumn>();
        }
    
        public int Id { get; set; }
        public int ReportId { get; set; }
        public string Content { get; set; }
        public Nullable<int> Order { get; set; }
        public string Index { get; set; }
        public Nullable<int> Code { get; set; }
    
        public virtual Report Report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportColumn> ReportColumns { get; set; }
    }
}
